name: e_commerce_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  appwrite: ^6.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.5
  flutter_swiper: ^1.1.6
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
